// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtYwlO1NfozJLUVyYJfporI8YePQao5-s',
    appId: '1:390184165791:android:19263eb0d4f46562c0ddaa',
    messagingSenderId: '390184165791',
    projectId: 'nita-auto',
    storageBucket: 'nita-auto.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9dMT6-Z5bFyAKkNuTkfpoTN4o_Srf8SU',
    appId: '1:390184165791:ios:32f9ed812f2e451ac0ddaa',
    messagingSenderId: '390184165791',
    projectId: 'nita-auto',
    storageBucket: 'nita-auto.appspot.com',
    iosBundleId: 'com.example.nitaAuto',
  );
  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyDrsVF9f62ay6JuJSntiT01Obd3iIKBTfc",
      authDomain: "nita-auto.firebaseapp.com",
      projectId: "nita-auto",
      storageBucket: "nita-auto.firebasestorage.app",
      messagingSenderId: "390184165791",
      appId: "1:390184165791:web:ee9c9160e9e13092c0ddaa");
}
